repository_type: pipeline

nf_core_version: 3.3.1

lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
  nextflow_config: false
  multiqc_config: false
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
    - nextflow_schema.json
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
    - nextflow_schema.json
  schema_lint: false
  schema_params: false
  schema_description: false

template:
  org: nf-core
  name: theiaprok_illumina_pe
  description: Theiagen Illumina Build Pipeline for Paired-End Reads of Prokaryotes
  author: Michal Babinski
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - igenomes
    - multiqc
    - fastqc
    - nf_schema
  is_nfcore: true
