
from dataclasses import dataclass
import typing
import typing_extensions

from flytekit.core.annotation import FlyteAnnotation

from latch.types.metadata import NextflowParameter, LatchParameter
from latch.types.file import LatchFile
from latch.types.directory import LatchDir, LatchOutputDir

# Import these into your `__init__.py` file:
#
# from .parameters import generated_parameters

@dataclass(frozen=True)
class Sample:
    sample: str
    read1: LatchFile
    read2: typing.Optional[LatchFile]

generated_parameters = {
    'table_id': LatchParameter(
        display_name="Input Table ID",
        batch_table_column=True,
        # Show a table picker instead of a normal int input
        _custom_ingestion="registry_table",
        section_title='Latch Table',
    ),
    'input': NextflowParameter(
        type=typing.List[Sample],
        samplesheet=True,
        samplesheet_type='csv',
        section_title='Input/output options',
        description='Path to comma-separated file containing information about the samples in the experiment.',
    ),
    'outdir': NextflowParameter(
        type=typing_extensions.Annotated[LatchDir, FlyteAnnotation({'output': True})],
        default=None,
        section_title=None,
        description='The output directory where the results will be saved. You have to use absolute paths to storage on Cloud infrastructure.',
    ),
    'samplename': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title='Sample configuration',
        description=None,
    ),
    'read1': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description=None,
    ),
    'read2': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description=None,
    ),
    'paired_end': NextflowParameter(
        type=typing.Optional[bool],
        default=True,
        section_title=None,
        description=None,
    ),
    'ont_data': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'assembly_only': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'skip_screen': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'workflow_series': NextflowParameter(
        type=typing.Optional[str],
        default='theiaprok',
        section_title=None,
        description=None,
    ),
    'min_reads': NextflowParameter(
        type=typing.Optional[int],
        default=7472,
        section_title='Quality control and filtering',
        description=None,
    ),
    'min_basepairs': NextflowParameter(
        type=typing.Optional[int],
        default=2241820,
        section_title=None,
        description=None,
    ),
    'min_genome_length': NextflowParameter(
        type=typing.Optional[int],
        default=100000,
        section_title=None,
        description=None,
    ),
    'max_genome_length': NextflowParameter(
        type=typing.Optional[int],
        default=18040666,
        section_title=None,
        description=None,
    ),
    'min_coverage': NextflowParameter(
        type=typing.Optional[int],
        default=10,
        section_title=None,
        description=None,
    ),
    'min_proportion': NextflowParameter(
        type=typing.Optional[int],
        default=40,
        section_title=None,
        description=None,
    ),
    'genome_length': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description=None,
    ),
    'trim_min_length': NextflowParameter(
        type=typing.Optional[int],
        default=50,
        section_title='Read processing and trimming',
        description=None,
    ),
    'trim_quality_min_score': NextflowParameter(
        type=typing.Optional[int],
        default=20,
        section_title=None,
        description=None,
    ),
    'trim_window_size': NextflowParameter(
        type=typing.Optional[int],
        default=4,
        section_title=None,
        description=None,
    ),
    'read_processing': NextflowParameter(
        type=typing.Optional[str],
        default='trimmomatic',
        section_title=None,
        description=None,
    ),
    'read_qc': NextflowParameter(
        type=typing.Optional[str],
        default='fastqc',
        section_title=None,
        description=None,
    ),
    'adapters': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description=None,
    ),
    'phix': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description=None,
    ),
    'fastp_args': NextflowParameter(
        type=typing.Optional[str],
        default='--detect_adapter_for_pe -g -5 20 -3 20',
        section_title=None,
        description=None,
    ),
    'assembler': NextflowParameter(
        type=typing.Optional[str],
        default='skesa',
        section_title='Assembly configuration',
        description=None,
    ),
    'min_contig_length': NextflowParameter(
        type=typing.Optional[int],
        default=200,
        section_title=None,
        description=None,
    ),
    'kmers': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description=None,
    ),
    'assembler_options': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description=None,
    ),
    'cg_pipe_opts': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description=None,
    ),
    'quast_min_contig_length': NextflowParameter(
        type=typing.Optional[int],
        default=500,
        section_title=None,
        description=None,
    ),
    'spades_type': NextflowParameter(
        type=typing.Optional[str],
        default='isolate',
        section_title=None,
        description=None,
    ),
    'call_pilon': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'pilon_min_mapping_quality': NextflowParameter(
        type=typing.Optional[int],
        default=60,
        section_title=None,
        description=None,
    ),
    'pilon_min_base_quality': NextflowParameter(
        type=typing.Optional[int],
        default=3,
        section_title=None,
        description=None,
    ),
    'pilon_min_depth': NextflowParameter(
        type=typing.Optional[float],
        default=0.25,
        section_title=None,
        description=None,
    ),
    'pilon_fix': NextflowParameter(
        type=typing.Optional[str],
        default='bases',
        section_title=None,
        description=None,
    ),
    'run_filter_contigs': NextflowParameter(
        type=typing.Optional[bool],
        default=True,
        section_title='Contig filtering',
        description=None,
    ),
    'filter_contigs_min_length': NextflowParameter(
        type=typing.Optional[int],
        default=200,
        section_title=None,
        description=None,
    ),
    'filter_contigs_min_coverage': NextflowParameter(
        type=typing.Optional[int],
        default=2,
        section_title=None,
        description=None,
    ),
    'filter_contigs_skip_length_filter': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'filter_contigs_skip_coverage_filter': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'filter_contigs_skip_homopolymer_filter': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'perform_characterization': NextflowParameter(
        type=typing.Optional[bool],
        default=True,
        section_title='Genome characterization',
        description=None,
    ),
    'call_ani': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'call_kmerfinder': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'call_resfinder': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'call_plasmidfinder': NextflowParameter(
        type=typing.Optional[bool],
        default=True,
        section_title=None,
        description=None,
    ),
    'call_abricate': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'call_midas': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'call_kraken': NextflowParameter(
        type=typing.Optional[bool],
        default=True,
        section_title=None,
        description=None,
    ),
    'call_stxtyper': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'call_poppunk': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'run_amr_search': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'run_merlin_magic': NextflowParameter(
        type=typing.Optional[bool],
        default=True,
        section_title=None,
        description=None,
    ),
    'genome_annotation': NextflowParameter(
        type=typing.Optional[str],
        default='prokka',
        section_title='Genome annotation',
        description=None,
    ),
    'bakta_db': NextflowParameter(
        type=typing.Optional[str],
        default='full',
        section_title=None,
        description=None,
    ),
    'expected_taxon': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description=None,
    ),
    'midas_db': NextflowParameter(
        type=typing.Optional[str],
        default='latch://tgn-latch-dev-database-2025.mount/midas/midas_db_v1.2.tar.gz',
        section_title='Database paths',
        description=None,
    ),
    'kraken_db': NextflowParameter(
        type=typing.Optional[str],
        default='latch://tgn-latch-dev-database-2025.mount/kraken2/terra_databases_kraken2_kraken2.kalamari_5.1.tar',
        section_title=None,
        description=None,
    ),
    'kmerfinder_db': NextflowParameter(
        type=typing.Optional[str],
        default='latch://tgn-latch-dev-database-2025.mount/kmerfinder/kmerfinder_bacteria_20230911.tar.gz',
        section_title=None,
        description=None,
    ),
    'gambit_db_genomes': NextflowParameter(
        type=typing.Optional[str],
        default='latch://tgn-latch-dev-database-2025.mount/gambit/gambit-metadata-2.0.1-20250505.gdb',
        section_title=None,
        description=None,
    ),
    'gambit_db_signatures': NextflowParameter(
        type=typing.Optional[str],
        default='latch://tgn-latch-dev-database-2025.mount/gambit/gambit-signatures-2.0.1-20250505.gs',
        section_title=None,
        description=None,
    ),
    'bakta_db_path': NextflowParameter(
        type=typing.Optional[str],
        default='latch://tgn-latch-dev-database-2025.mount/bakta/',
        section_title=None,
        description=None,
    ),
    'resfinder_db_res': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description=None,
    ),
    'resfinder_db_point': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description=None,
    ),
    'plasmidfinder_db': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description=None,
    ),
    'plasmidfinder_db_path': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description=None,
    ),
    'plasmidfinder_method_path': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description=None,
    ),
    'vibecheck_vibrio_barcodes': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description=None,
    ),
    'abricate_db': NextflowParameter(
        type=typing.Optional[str],
        default='vfdb',
        section_title='AMR analysis',
        description=None,
    ),
    'amrfinder_min_percent_identity': NextflowParameter(
        type=typing.Optional[float],
        default=0.9,
        section_title=None,
        description=None,
    ),
    'amrfinder_min_percent_coverage': NextflowParameter(
        type=typing.Optional[float],
        default=0.5,
        section_title=None,
        description=None,
    ),
    'amrfinder_detailed_drug_class': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'amrfinder_hide_point_mutations': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'amrfinder_separate_betalactam_genes': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'resfinder_organism': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description=None,
    ),
    'resfinder_acquired': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'resfinder_min_percent_coverage': NextflowParameter(
        type=typing.Optional[float],
        default=0.5,
        section_title=None,
        description=None,
    ),
    'resfinder_min_percent_identity': NextflowParameter(
        type=typing.Optional[float],
        default=0.9,
        section_title=None,
        description=None,
    ),
    'resfinder_call_pointfinder': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'plasmidfinder_min_percent_coverage': NextflowParameter(
        type=typing.Optional[float],
        default=0.6,
        section_title=None,
        description=None,
    ),
    'plasmidfinder_min_percent_identity': NextflowParameter(
        type=typing.Optional[float],
        default=0.9,
        section_title=None,
        description=None,
    ),
    'mlst_nopath': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title='Typing and characterization',
        description=None,
    ),
    'mlst_scheme': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description=None,
    ),
    'mlst_min_percent_identity': NextflowParameter(
        type=typing.Optional[int],
        default=95,
        section_title=None,
        description=None,
    ),
    'mlst_min_percent_coverage': NextflowParameter(
        type=typing.Optional[int],
        default=10,
        section_title=None,
        description=None,
    ),
    'mlst_minscore': NextflowParameter(
        type=typing.Optional[int],
        default=50,
        section_title=None,
        description=None,
    ),
    'stxtyper_enable_debugging': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'kaptive_start_end_margin': NextflowParameter(
        type=typing.Optional[int],
        default=10,
        section_title=None,
        description=None,
    ),
    'kaptive_min_percent_coverage': NextflowParameter(
        type=typing.Optional[int],
        default=90,
        section_title=None,
        description=None,
    ),
    'kaptive_min_percent_identity': NextflowParameter(
        type=typing.Optional[int],
        default=80,
        section_title=None,
        description=None,
    ),
    'kaptive_low_gene_percent_identity': NextflowParameter(
        type=typing.Optional[int],
        default=95,
        section_title=None,
        description=None,
    ),
    'abricate_abaum_min_percent_identity': NextflowParameter(
        type=typing.Optional[int],
        default=80,
        section_title=None,
        description=None,
    ),
    'abricate_abaum_min_percent_coverage': NextflowParameter(
        type=typing.Optional[int],
        default=80,
        section_title=None,
        description=None,
    ),
    'lissero_min_percent_identity': NextflowParameter(
        type=typing.Optional[int],
        default=95,
        section_title=None,
        description=None,
    ),
    'lissero_min_percent_coverage': NextflowParameter(
        type=typing.Optional[int],
        default=95,
        section_title=None,
        description=None,
    ),
    'ectyper_o_min_percent_identity': NextflowParameter(
        type=typing.Optional[int],
        default=90,
        section_title=None,
        description=None,
    ),
    'ectyper_h_min_percent_identity': NextflowParameter(
        type=typing.Optional[int],
        default=95,
        section_title=None,
        description=None,
    ),
    'ectyper_o_min_percent_coverage': NextflowParameter(
        type=typing.Optional[int],
        default=90,
        section_title=None,
        description=None,
    ),
    'ectyper_h_min_percent_coverage': NextflowParameter(
        type=typing.Optional[int],
        default=50,
        section_title=None,
        description=None,
    ),
    'ectyper_verify': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'ectyper_print_alleles': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'spatyper_do_enrich': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'pbptyper_database': NextflowParameter(
        type=typing.Optional[str],
        default='[]',
        section_title=None,
        description=None,
    ),
    'pbptyper_min_percent_identity': NextflowParameter(
        type=typing.Optional[int],
        default=95,
        section_title=None,
        description=None,
    ),
    'pbptyper_min_percent_coverage': NextflowParameter(
        type=typing.Optional[int],
        default=95,
        section_title=None,
        description=None,
    ),
    'emmtyper_wf': NextflowParameter(
        type=typing.Optional[str],
        default='blast',
        section_title=None,
        description=None,
    ),
    'emmtyper_cluster_distance': NextflowParameter(
        type=typing.Optional[int],
        default=500,
        section_title=None,
        description=None,
    ),
    'emmtyper_min_percent_identity': NextflowParameter(
        type=typing.Optional[int],
        default=95,
        section_title=None,
        description=None,
    ),
    'emmtyper_culling_limit': NextflowParameter(
        type=typing.Optional[int],
        default=5,
        section_title=None,
        description=None,
    ),
    'emmtyper_mismatch': NextflowParameter(
        type=typing.Optional[int],
        default=4,
        section_title=None,
        description=None,
    ),
    'emmtyper_align_diff': NextflowParameter(
        type=typing.Optional[int],
        default=5,
        section_title=None,
        description=None,
    ),
    'emmtyper_gap': NextflowParameter(
        type=typing.Optional[int],
        default=2,
        section_title=None,
        description=None,
    ),
    'emmtyper_min_perfect': NextflowParameter(
        type=typing.Optional[int],
        default=15,
        section_title=None,
        description=None,
    ),
    'emmtyper_min_good': NextflowParameter(
        type=typing.Optional[int],
        default=15,
        section_title=None,
        description=None,
    ),
    'emmtyper_max_size': NextflowParameter(
        type=typing.Optional[int],
        default=2000,
        section_title=None,
        description=None,
    ),
    'hicap_min_gene_percent_coverage': NextflowParameter(
        type=typing.Optional[float],
        default=0.8,
        section_title=None,
        description=None,
    ),
    'hicap_min_gene_depth': NextflowParameter(
        type=typing.Optional[float],
        default=0.7,
        section_title=None,
        description=None,
    ),
    'hicap_min_gene_length': NextflowParameter(
        type=typing.Optional[int],
        default=60,
        section_title=None,
        description=None,
    ),
    'hicap_min_gene_percent_identity': NextflowParameter(
        type=typing.Optional[float],
        default=0.8,
        section_title=None,
        description=None,
    ),
    'srst2_min_percent_coverage': NextflowParameter(
        type=typing.Optional[int],
        default=90,
        section_title=None,
        description=None,
    ),
    'srst2_max_divergence': NextflowParameter(
        type=typing.Optional[int],
        default=10,
        section_title=None,
        description=None,
    ),
    'srst2_min_depth': NextflowParameter(
        type=typing.Optional[int],
        default=5,
        section_title=None,
        description=None,
    ),
    'srst2_min_edge_depth': NextflowParameter(
        type=typing.Optional[int],
        default=2,
        section_title=None,
        description=None,
    ),
    'srst2_gene_max_mismatch': NextflowParameter(
        type=typing.Optional[int],
        default=10,
        section_title=None,
        description=None,
    ),
    'abricate_vibrio_min_percent_identity': NextflowParameter(
        type=typing.Optional[int],
        default=80,
        section_title=None,
        description=None,
    ),
    'abricate_vibrio_min_percent_coverage': NextflowParameter(
        type=typing.Optional[int],
        default=80,
        section_title=None,
        description=None,
    ),
    'virulencefinder_database': NextflowParameter(
        type=typing.Optional[str],
        default='virulence_ecoli',
        section_title='Virulence analysis',
        description=None,
    ),
    'virulencefinder_min_percent_coverage': NextflowParameter(
        type=typing.Optional[float],
        default=0.6,
        section_title=None,
        description=None,
    ),
    'virulencefinder_min_percent_identity': NextflowParameter(
        type=typing.Optional[float],
        default=0.9,
        section_title=None,
        description=None,
    ),
    'tbp_parser_config': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title='Tuberculosis analysis',
        description=None,
    ),
    'tbp_parser_sequencing_method': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description=None,
    ),
    'tbp_parser_operator': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description=None,
    ),
    'tbp_parser_min_depth': NextflowParameter(
        type=typing.Optional[int],
        default=10,
        section_title=None,
        description=None,
    ),
    'tbp_parser_min_frequency': NextflowParameter(
        type=typing.Optional[float],
        default=0.1,
        section_title=None,
        description=None,
    ),
    'tbp_parser_min_read_support': NextflowParameter(
        type=typing.Optional[int],
        default=10,
        section_title=None,
        description=None,
    ),
    'tbp_parser_min_percent_coverage': NextflowParameter(
        type=typing.Optional[int],
        default=100,
        section_title=None,
        description=None,
    ),
    'tbp_parser_coverage_regions_bed': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description=None,
    ),
    'tbp_parser_add_cycloserine_lims': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'tbp_parser_debug': NextflowParameter(
        type=typing.Optional[bool],
        default=True,
        section_title=None,
        description=None,
    ),
    'tbp_parser_tngs': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'tbp_parser_rrs_frequncy': NextflowParameter(
        type=typing.Optional[float],
        default=0.1,
        section_title=None,
        description=None,
    ),
    'tbp_parser_rrs_read_support': NextflowParameter(
        type=typing.Optional[int],
        default=10,
        section_title=None,
        description=None,
    ),
    'tbp_parser_rr1_frequency': NextflowParameter(
        type=typing.Optional[float],
        default=0.1,
        section_title=None,
        description=None,
    ),
    'tbp_parser_rr1_read_support': NextflowParameter(
        type=typing.Optional[int],
        default=10,
        section_title=None,
        description=None,
    ),
    'tbp_parser_rpob499_frequency': NextflowParameter(
        type=typing.Optional[float],
        default=0.1,
        section_title=None,
        description=None,
    ),
    'tbp_parser_etha237_frequency': NextflowParameter(
        type=typing.Optional[float],
        default=0.1,
        section_title=None,
        description=None,
    ),
    'tbp_parser_expert_rule_regions_bed': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description=None,
    ),
    'poppunk_gps_db_url': NextflowParameter(
        type=typing.Optional[str],
        default='https://gps-project.cog.sanger.ac.uk/GPS_6.tar.gz',
        section_title='Population genomics',
        description=None,
    ),
    'poppunk_gps_external_clusters_url': NextflowParameter(
        type=typing.Optional[str],
        default='https://gps-project.cog.sanger.ac.uk/GPS_v6_external_clusters.csv',
        section_title=None,
        description=None,
    ),
    'publish_dir_mode': NextflowParameter(
        type=typing.Optional[str],
        default='copy',
        section_title='System and output',
        description=None,
    ),
    'email': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description=None,
    ),
    'email_on_fail': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description=None,
    ),
    'plaintext_email': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'monochrome_logs': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'hook_url': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description=None,
    ),
    'help_full': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'show_hidden': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title=None,
        description=None,
    ),
    'pipelines_testdata_base_path': NextflowParameter(
        type=typing.Optional[str],
        default='https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/',
        section_title=None,
        description=None,
    ),
    'version': NextflowParameter(
        type=typing.Optional[bool],
        default=None,
        section_title='Generic options',
        description='Display version and exit.',
    ),
    'validate_params': NextflowParameter(
        type=typing.Optional[bool],
        default=True,
        section_title=None,
        description='Boolean whether to validate parameters against the schema at runtime',
    ),
    'trace_report_suffix': NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description='Suffix to add to the trace report filename. Default is the date and time in the format yyyy-MM-dd_HH-mm-ss.',
    ),
}

